# Generated by Django 4.2 on 2024-12-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pedido_pedidoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
